on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
      - name: Run github-to-json
        run: |
          npm install --global github-to-json
          github-to-json tdahlstrom actions-test -t ${{ secrets.TOKEN }} -o files.json
