jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run github-to-json
        run: |
          npm install github-to-json
          github-to-json tdahlstrom actions-test -t ${{ secrets.TOKEN }} > files.json
      - Commit changes
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          git add files.json
          git commit -m "Update files.json"
          git push
          
